version: 2.1

executors:
 
  node-executor:
    docker:
      - image: circleci/python:3.8  
    working_directory: ~/repo

jobs:
  build:
    executor: node-executor
    steps:
      - checkout  # pu;l code from the repo
      - run:
          name: Set up Node.js and dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y nodejs npm
            sudo npm install -g pm2
            npm install  # Install app dependencies
      - run:
          name: Run tests
          command: |
            npm test  # Add your test command here

  deploy:
    executor: node-executor
    steps:
      - checkout  # get code from the repo again if needed
      - run:
          name: Install dependencies for deployment
          command: |
            sudo apt-get update && sudo apt-get install -y nodejs npm
            sudo npm install -g pm2
      - run:
          name: Make deploy.sh executable
          command: chmod +x deploy.sh
      - run:
          name: Execute deploy.sh
          command: ./deploy.sh  # run deploy script

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build  # make sure deploy runs only after build is successful
